### ISSUE TITLE
Nothing to see here

### ISSUE THREAD

**Issue by rojtjo** [vespakoen/ontheweb#1]
Hello,

This repository seems to be empty. Any future plans for it?

Best regards,
Roj

**Comment by vespakoen** [comment]
Yes, I am planning to put my personal website here, and the websites for my open source projects.

It really is going to be the bee's knees =)

**Comment by vespakoen** [comment]
Can I close this?

Long time no response...

Let me know if you have any more issues

**Comment by rojtjo** [comment]
Love it!
